"""add phone column to employees

Revision ID: 90b09a846f6e
Revises: 
Create Date: 2026-03-03 00:23:03.114225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b09a846f6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable (allows NULL)
    op.add_column('employees', sa.Column('phone', sa.String(length=20), nullable=True))
    
    # Step 2: Set default values for existing rows
    # You can set a placeholder or update based on some logic
    op.execute("UPDATE employees SET phone = '000-000-0000' WHERE phone IS NULL")
    
    # Step 3: Now make it NOT NULL
    op.alter_column('employees', 'phone',
                    existing_type=sa.String(length=20),
                    nullable=False)
    
    # Step 4: Create index
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###
